# Generated by Django 4.2.6 on 2023-10-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train_station_resource", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={
                "verbose_name": "Crew member",
                "verbose_name_plural": "Crew members",
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="crew",
            field=models.ManyToManyField(to="train_station_resource.crew"),
        ),
    ]
