# Generated by Django 4.2.6 on 2023-10-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train_station_resource", "0002_alter_crew_options_trip_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="traintype",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
