# Generated by Django 4.2.6 on 2023-10-19 14:44

from django.db import migrations, models
import train_station_resource.models


class Migration(migrations.Migration):
    dependencies = [
        ("train_station_resource", "0003_traintype_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=train_station_resource.models.train_image_file_path,
            ),
        ),
    ]
